Repository jenkinsci/hashicorp-vault-plugin, pull requests merged in 2019-07, with the labels that each got.

#31 update POM
  pom.xml
Labels: chore

#32 Enable Release Drafter for the plugin
  .github/release-drafter.yml
Labels: internal

#25 Fix/null secret values
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
Labels: bug

#30 Add retries to loginByGCP() method
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultGCPCredential.java
Labels: enhancement
