Repository jenkinsci/hashicorp-vault-plugin, pull requests merged in 2019-10, with the labels that each got.

#55 [JENKINS-59247] - fix "Fail if path is not found"
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
  src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
  src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
Labels: bug

#58 use versions from BOM
  pom.xml
Labels: dependencies

#60 Bump vault from 1.12.0 to 1.12.2
  pom.xml
Labels: dependencies

#59 add integration tests for build wrapper against vault container
  .github/workflows/maven.yml
  .gitignore
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
  src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
  src/test/java/com/datapipe/jenkins/vault/it/buildwrapper/SSLTest.java
  src/test/java/com/datapipe/jenkins/vault/util/TestConstants.java
  src/test/java/com/datapipe/jenkins/vault/util/VaultContainer.java
  src/test/resources/com/datapipe/jenkins/vault/util/gencert.sh
  src/test/resources/com/datapipe/jenkins/vault/util/ssl/root-cert.pem
  src/test/resources/com/datapipe/jenkins/vault/util/ssl/root-privkey.pem
  src/test/resources/com/datapipe/jenkins/vault/util/ssl/vault-cert.pem
  src/test/resources/com/datapipe/jenkins/vault/util/ssl/vault-privkey.pem
  src/test/resources/com/datapipe/jenkins/vault/util/startup.sh
Labels: chore

#64 fix mvn flags on powershell
  .github/workflows/maven.yml
Labels: chore
