Repository jenkinsci/hashicorp-vault-plugin, pull requests merged in 2019-08, with the labels that each got.

#29 Update documentation for KV 2 Engine and backward compatibility
  README.md
Labels: documentation

#38 enable incrementals artifacts
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#39 add travis ci
  .travis.yml
Labels: chore

#43 Add codestyle, checkstyle. Switch to SpotBugs annotations. Format!
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .mvn/checkstyle.xml
  pom.xml
  src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
  src/main/java/com/datapipe/jenkins/vault/VaultDisposer.java
  src/main/java/com/datapipe/jenkins/vault/configuration/FolderVaultConfiguration.java
  src/main/java/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration.java
  src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfigResolver.java
  src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
  src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultGCPCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenCredentialBinding.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenFileCredential.java
  src/main/java/com/datapipe/jenkins/vault/exception/VaultPluginException.java
  src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java
  src/main/java/com/datapipe/jenkins/vault/model/VaultSecret.java
  src/main/java/com/datapipe/jenkins/vault/model/VaultSecretValue.java
  src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/help-authTokenCredentialId.html
  src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/help-tokenFilePath.html
  src/main/resources/com/datapipe/jenkins/vault/configuration/FolderVaultConfiguration/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/help-engineVersion.html
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential/credentials.jelly
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGCPCredential/credentials.jelly
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential/credentials.jelly
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultTokenCredential/credentials.jelly
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultTokenCredentialBinding/config-variables.jelly
  src/main/resources/com/datapipe/jenkins/vault/credentials/VaultTokenFileCredential/credentials.jelly
  src/main/resources/com/datapipe/jenkins/vault/model/VaultSecret/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/model/VaultSecret/help-engineVersion.html
  src/main/resources/com/datapipe/jenkins/vault/model/VaultSecret/help-path.html
  src/main/resources/com/datapipe/jenkins/vault/model/VaultSecretValue/config.jelly
  src/main/resources/com/datapipe/jenkins/vault/model/VaultSecretValue/help-envVar.html
  src/main/resources/index.jelly
  src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperWithMockAccessor.java
  src/test/java/com/datapipe/jenkins/vault/configuration/FolderVaultConfigurationSpec.java
  src/test/java/com/datapipe/jenkins/vault/configuration/VaultConfigurationSpec.java
  src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java
  src/test/java/com/datapipe/jenkins/vault/it/VaultTokenCredentialBindingIT.java
  src/test/java/com/datapipe/jenkins/vault/it/folder/FolderIT.java
  src/test/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilterSpec.java
Labels: chore

#35 Add vault secret source for JCasC
  pom.xml
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAppRoleAuthenticator.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticator.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticatorWithExpiration.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSingleTokenAuthenticator.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultUserPassAuthenticator.java
  src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
  src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultTestUtil.java
  src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vault.yml
  src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vaultTest_adminPolicy.hcl
  src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vaultTest_cascFile
Labels: enhancement

#48 add missing annotations
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultGCPCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential.java
  src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenCredentialBinding.java
  src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java
Labels: chore

#46 simplify pipeline snippet
  README.md
Labels: documentation

#49 add vault agent documentation
  .editorconfig
  README.md
  pom.xml
Labels: documentation

#50 use UTF_8 when converting error response
  README.md
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
Labels: skip-changelog
