Repository jenkinsci/hashicorp-vault-plugin, pull requests merged in 2020-01, with the labels that each got.

#67 Support prefixPath field
  README.md
  pom.xml
  src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
  src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialImpl.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
  src/test/java/com/datapipe/jenkins/vault/configuration/VaultConfigurationSpec.java
  src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
  src/test/java/com/datapipe/jenkins/vault/util/TestConstants.java
  src/test/java/com/datapipe/jenkins/vault/util/VaultTestUtil.java
  src/test/resources/com/datapipe/jenkins/vault/util/vaultTest_adminPolicy.hcl
Labels: dependencies, enhancement

#66 CasC: allow login by Kubernetes ServiceAccount
  README.md
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticator.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultKubernetes.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultKubernetesAuthenticator.java
  src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
Labels: enhancement

#70 [JENKINS-59836] - Do not serialize VaultConfig
  src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
Labels: bug
